### ISSUE TITLE
Crash on start mc 1.20.1 with MnA version 3.0.0.17

### ISSUE THREAD

**Issue by Eonwe98** [SoSly/ArcaneAdditions#100]
The most recent release of MnA version 3.0.0.17 on loading will crash the game before even finishing loading when Arcane Additions is installed. Crash report and log provided.

[crash-2024-07-07_13.45.30-client.txt](https://github.com/user-attachments/files/16120726/crash-2024-07-07_13.45.30-client.txt)
[latest.log](https://github.com/user-attachments/files/16120725/latest.log)

**Comment by nivthefox** [comment]
Will be fixed in 1.9.5
