### ISSUE TITLE
Flying companions tend to not follow you

### ISSUE THREAD

**Issue by ViewPointGames** [SoSly/ArcaneAdditions#85]
While testing I found that flying mobs do not seem to indicate any action that resembles moving towards their bound player, aside from the teleport action when they are too far from you.

I tested mna pixies, they were just constantly flying in one direction without any logical reason known to me.
I tested parrots, they behave normally but likely due to being a vanilla pet as well.
Bats I did not test, didnt have the time to do so.
I also tried sunbirds from Alex's mobs, but they just flew straight up without even teleporting back to me, I assume that their AI is coded specifically for them to search world height and stay there.

**Comment by nivthefox** [comment]
Yeah, this is a known issue with some of them (bats in particular are bad about it).  I'm still working on improving mob AI and this is one of the things I'm thinking about. 

Sunbirds, however, are just _designed_ to do that. Not much I can do there.
