### ISSUE TITLE
Codex mistake[?]

### ISSUE THREAD

**Issue by xiaoknya** [SoSly/ArcaneAdditions#87]
![image](https://github.com/SoSly/ArcaneAdditions/assets/63701701/92598d50-a353-49d9-9244-156aaf912c4f)
![image](https://github.com/SoSly/ArcaneAdditions/assets/63701701/508c6117-bea4-44ba-839e-6f84e8b49293)
Hello! The Ritual of Inculcation and the Ritual of Familiar Magic seem to be the same thing, but they have different names. Perhaps one of them is correct or maybe it was done intentionally this way? If you could tell me how it is, that would be great. Thanks!

**Comment by nivthefox** [comment]
Ohh good catch. Ritual of Inculcation is the correct name.  I'll fix that in the next update.
