### ISSUE TITLE
Crash upon opening a chest that I presume contained Mana and Artifice items.

### ISSUE THREAD

**Issue by border999** [SoSly/ArcaneAdditions#89]
https://gist.github.com/border999/9fb9aecf0ea581769f4e925c3269f03f
ArcaneAdditions-1.20.1-forge-1.9.3
mna-forge-1.20.1-3.0.0.14-all
Opening issue on both sides to ensure both mod authors are aware.

**Comment by nivthefox** [comment]
This is definitely an AA bug. Looks like it's specific to polymorph; I've had several complaints about it.  I'm testing and trying to figure out the resolution.  Thanks for the report.
