### ISSUE TITLE
Spell component strip not contributing xp to magic level

### ISSUE THREAD

**Issue by nanakisan** [SoSly/ArcaneAdditions#90]
Per the title the component strip is not contributing to magic level. This is presently happening with MnA 3.0.0.14

**Comment by nivthefox** [comment]
As in you don't gain experience from casting it?

**Comment by nanakisan** [comment]
Correct. No rote progress or xp to magic level.

**Comment by nivthefox** [comment]
Good catch!  This is fixed in the next version. :)
